version: '2'
services:
  app:
    build:
      context: ./s1
    volumes:
      - ./s1:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
  app2:
    build:
      context: ./s2
    volumes:
      - ./s2:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3001:3001
    mem_limit: 128M
  mongo:
    container_name: mongo
    image: mongo
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
    ports:
     - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
volumes:
 mongodb:
 mongodb_config:
 node_modules:
